Further improvements and clean ups
DFDLSchemas/faketdl pull request #6
Opened 2024-09-27 16:21 UTC by mbeckerle

Change type names to reflect units of measure (a useful practice makes things a bit more self-documenting)

Added tests to subsume all the ones in the Owl DFDL training.

Some renaming to make things more uniform. Tests of single messages - the files and tests have "msg" in their names. Tests of files of multiple messages have "file" in their names.

2024-09-27 16:26 UTC, mbeckerle commented
@jadams-tresys Any comments at all on fakeTDL are welcome. 

From here on I will make sure any changes to it are PRs so you are kept aware.

The training will essentially build this schema bit by bit. Minor differences.

2024-09-30 14:30 UTC, olabusayoT requested changes
#7 is not yet taken care of

2024-09-30 14:30 UTC, olabusayoT commented on src/fakeTDL.dfdl.xsd
> +  <xs:element name="fakeTDL" type="fakeTDL:fakeTDLType" dfdl:ref="fakeTDL:msg">
We are still reffing this element down below in fakeTDLFile? See #7

2024-09-30 14:37 UTC, mbeckerle commented on src/fakeTDL.dfdl.xsd
> +  <xs:element name="fakeTDL" type="fakeTDL:fakeTDLType" dfdl:ref="fakeTDL:msg">
Ah. I fixed it in the training materials, not here. 
Thanks.

2024-09-30 14:41 UTC, mbeckerle commented on src/fakeTDL.dfdl.xsd
> +  <xs:element name="fakeTDL" type="fakeTDL:fakeTDLType" dfdl:ref="fakeTDL:msg">
Pushed fix for this.

2024-09-30 17:52 UTC, olabusayoT approved these changes
+1

2024-10-03 22:22 UTC, jadams-tresys approved these changes
+1

2024-10-28 16:11 UTC, merged